version: "3"
services:
  api.openfileplatform.com:
    privileged: true
    stdin_open: true
    tty: true
    build: .
    image: api.openfileplatform.com
    #    container_name: api.openfileplatform.com
    restart: always
    volumes:
      - /docker/deploy/api.openfileplatform.com/configs:/apps/configs
      - /docker/deploy/api.openfileplatform.com/logs:/apps/logs
    ports:
      - "8000:8000"
    command:
      - /apps/golang_app