#mysql Document management system
[mysql]
host = "39.99.146.111"
ports = 3306
username = "dev_go"
password = "dev_go2021"
DATABASE = "OpenFilePlatform"
CHARSET = "utf8mb4"

[redis]
host = "127.0.0.1"
port = 6379
password = ""